---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-puma
  labels:
    app: demoapp
    component: puma
spec:
  ports:
    - protocol: TCP
      port: 3000
  selector:
    app: demoapp
    component: puma
