default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "0.0.0.0" } %>

development:
  <<: *default
  database: demoapp_development

test:
  <<: *default
  database: demoapp_test

production:
  <<: *default
  database: demoapp_production
